### ISSUE TITLE
Can't save cropped image.

### ISSUE THREAD

**Issue by mfrr** [openalpr/plate_tagger#9]
I'm trying to save the cropped image, but the save button keeps deactivate.

![plate](https://user-images.githubusercontent.com/7936443/59536798-244c5b80-8ecb-11e9-8491-0dacf0bb2ca2.png)

**Comment by mfrr** [comment]
Forget, I already figured out.

**Comment by mohamednizar** [comment]
@mfrr ,I'm facing the same problem, can you help me?

**Comment by mfrr** [comment]
@mohamednizar you need to place the plate's corners in the License plate selection window. To do that just click on the image. After that the save button will be activated.
